### ISSUE TITLE
PNG Mime type already registered with Rails 3.2

### ISSUE THREAD

**Issue by peternash** [samvincent/rqrcode-rails3#11]
In Rails 3.2 the PNG Mime Type is already registered so you see this error each time Rails starts:

/actionpack-3.2.1/lib/action_dispatch/http/mime_type.rb:101: warning: already initialized constant PNG

Changing line 8 of rqrcode-rails3.rb as follows prevents the error:

  Mime::Type.register "image/png",     :png  unless Mime::Type.lookup_by_extension(:png)

**Comment by samvincent** [comment]
That sounds right. In fact, that's better for previous versions of rails as well as there are other commonly used gems that define that mime type as well. Feel free to make a pull request, otherwise I'll add this when I get the chance.

**Comment by samvincent** [comment]
I just merged and release 0.1.4 with your commit. Thank you very much, Peter.
