### ISSUE TITLE
Consider the rqrcode-with-patches gem

### ISSUE THREAD

**Issue by bdewater** [samvincent/rqrcode-rails3#18]
Just a tip :smile: We've rolled our own solution for supporting Google Authenticator at my employer before I came across your gem. We used https://github.com/bjornblomqvist/rqrcode because it offers a few improvements over the original (and unmaintained) rQRCode gem:
- Rendering PNG in Ruby with chunky_png, so you don't need ImageMagick
- Chunky_png has a to_data_url function, so you can inline the QR code in HTML and you don't need to store files
- This workaround for IE7 for data URI's is worth mentioning: http://www.phpied.com/mhtml-when-you-need-data-uris-in-ie7-and-under/
- QR code length can be calculated automatically, so you don't get errors such as https://github.com/whomwah/rqrcode/issues/15 if you don't set a fixed length

**Comment by samvincent** [comment]
Patches accepted! I'm not currently using this in production myself. I like the `to_data_url` functionality.
