### ISSUE TITLE
user should be able to set exact percent error correction

### ISSUE THREAD

**Issue by Tectract** [samvincent/rqrcode-rails3#19]
I'm trying to create the smallest possible QR codes and I'd like to be able to set error correction to 0%.

**Comment by samvincent** [comment]
I don't believe the spec supports it. See wiki error correction section: [https://en.wikipedia.org/wiki/QR_code](https://en.wikipedia.org/wiki/QR_code#Error_correction).

In anycase, this project just wraps and renders qr codes generated by [RQRCode](http://www.rubydoc.info/gems/rqrcode), so it won't be able to do things that aren't supported by that project.
