### ISSUE TITLE
uninitialized constant Mime::SVG

### ISSUE THREAD

**Issue by JWesorick** [samvincent/rqrcode-rails3#5]
I keep getting

> uninitialized constant Mime::SVG
> when trying to use this. I followed the directions on the ReadMe. Is there more that I need to do that is not listed?

**Comment by bradleypriest** [comment]
The latest gem has an issue which has been fixed in master https://github.com/samvincent/rqrcode-rails3/commit/e4c949a516b4992acc2bd46982fb3e098722a360 but hasn't been rereleased. Either require the master branch in your gemfile or use `gem 'rqrcode-rails3', :require => 'rqrcode_rails3'`

**Comment by samvincent** [comment]
Just released v0.1.2. Should work just fine.
