### ISSUE TITLE
Issue when try to format to PNG

### ISSUE THREAD

**Issue by felipe3246** [samvincent/rqrcode-rails3#7]
I'm using the example to format a qrcode into png like the demonstration in source, but it doesn't work. 

I'm using 

Rails 3.0.9
Ruby 1.9.2
rqrcode-rails3 0.1.3
mini_magick 3.3
subexec 0.1.0 

The error is this.

Command ("identify -ping C:/Users/Felipe/AppData/Local/Temp/mini_magick20110831-6140-19lh3zb") failed: {:status_code=>1, :output=>""}

**Comment by samvincent** [comment]
Can you use mini_magick to do anything with your install? It's my gut feeling there's something wrong with your ImageMagick install.

**Comment by felipe3246** [comment]
if i test with svg ot works fine. 
Just png that makes this. 

I reinstalled my gems and it continues not working. 
my OS is Windows, is that a kind of problem?

**Comment by samvincent** [comment]
SVG just uses ruby so it's pretty trivial to get working. PNG requires the C lib ImageMagick to create the PNG files from SVG output.

You may want to look at http://www.imagemagick.org/script/binary-releases.php to install it for windows.

And you may want to test creating files with mini_magick on it's own before requesting support for this project as it is a pre-requisite to render PNG files.
